title: Douglas Hudson Walker
description: Experienced Graduate Software Engineer & Application Developer
google_analytics:
theme: jekyll-theme-midnight

remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
